/* Generated by shared/assemble.mjs - do not edit by hand. */
window.COOKBOOK_CONCEPTS = [
  {
    "folder": "proposal-01",
    "id": "proposal-01",
    "name": "Editorial Gallery",
    "tagline": "A printed cookbook opening spread translated into a calm, photo-led interface.",
    "thesis": "Paul's Cookbook should feel like a carefully art-directed personal volume before it feels like software: the masthead carries the identity, chapter dividers pace the collection, and every recipe reads as a plated photograph with quiet typographic facts underneath.",
    "palette": {
      "light": {
        "paper": "#f6efe3",
        "plate": "#fffaf0",
        "ink": "#15130f",
        "mutedInk": "#625b50",
        "accent": "#283f8f"
      },
      "dark": {
        "paper": "#0d0d10",
        "plate": "#17171d",
        "ink": "#f4eddf",
        "mutedInk": "#c2b7a5",
        "accent": "#9fb6ff"
      }
    },
    "typography": {
      "display": "Fraunces with Georgia fallback for the oversized masthead and chapter openers",
      "ui": "Inter/system-ui for controls and readable bilingual body copy",
      "data": "JetBrains Mono/ui-monospace for numerals, counts, prices, and index labels"
    },
    "moves": [
      "Treat the first viewport as a masthead spread: huge serif wordmark, quiet caption, and a single underlined search line.",
      "Render category sections as cookbook chapters with oversized numerals, hairline rules, large names, and tracked recipe counts.",
      "Make each card a plate: framed photo first, then full untruncated title and hairline-separated prep/price data below the image.",
      "Move filters, category navigation, more links, and preferences into a right-side Contents / Index drawer with printed-book rules.",
      "Use one restrained ink-blue accent against paper and ink, with a black-stock dark theme rather than a simple inversion.",
      "Keep motion minimal: slow ink fades and a measured drawer slide, disabled for reduced-motion users."
    ],
    "tradeoffs": [
      "The two-column grid is intentionally preserved on desktop, which shows fewer recipes per row but keeps the signature gallery rhythm.",
      "Metadata is typographic rather than iconographic, so the cards are calmer but require reading labels instead of scanning symbols.",
      "The drawer centralizes secondary controls; this protects the masthead but adds one tap for filter discovery."
    ]
  },
  {
    "folder": "proposal-02",
    "id": "proposal-02",
    "name": "Tactile Depth",
    "tagline": "A dark-first premium app shell where real recipe photography glows against layered near-black surfaces.",
    "thesis": "Paul's Cookbook should feel like a funded, high-craft mobile product: compact controls, cinematic food imagery, precise metadata, and a floating side drawer that turns utility into something tactile. The design refuses the generic recipe-site card wall by treating every recipe as a polished object and every control as part of a browsing cockpit.",
    "palette": {
      "dark": {
        "background": "#080706",
        "surface": "#17120e",
        "surfaceRaised": "#211914",
        "ink": "#fff8ee",
        "muted": "#c8b7a3",
        "accent": "#e79d49",
        "accentGlow": "#ffbd6e"
      },
      "light": {
        "background": "#f4eee5",
        "surface": "#fffdf8",
        "surfaceRaised": "#f2e5d4",
        "ink": "#211711",
        "muted": "#6d5748",
        "accent": "#b96520",
        "accentGlow": "#d98432"
      }
    },
    "typography": {
      "display": "Fraunces if present, Georgia fallback",
      "ui": "Inter if present, system UI fallback",
      "numeric": "JetBrains Mono if present, SFMono/Consolas fallback",
      "scale": "16px base with a 12.5% large-text preference; card titles never below 16px, metadata never below 13px, micro labels never below 11px"
    },
    "moves": [
      "Dark-first layered surfaces with one committed copper/amber accent and restrained optical glow.",
      "A sticky morphing control dock combines search, live count, sort direction, and category grouping without stealing browse space.",
      "Recipe cards behave like tactile objects: rounded, lifted, image-led, with no floating black metadata chips from the incumbent design.",
      "Prep time and price use inline tabular numerals with quieter units and explicit partial/unavailable price states.",
      "The side menu is a floating panel with elevated depth, focus trapping, body scroll lock, tactile filter chips, category jumps, more links, and preferences.",
      "Light mode is warm porcelain and copper with its own depth system rather than a naive dark inversion.",
      "Empty state, focus rings, reduced motion, long Romanian titles, and 320px no-overflow behavior are designed as first-class seams."
    ],
    "tradeoffs": [
      "The hero is intentionally atmospheric but compact; it uses real catalogue photos without adding editorial claims or recommendations.",
      "The control dock stacks on narrow screens to preserve 44px touch targets and readable text instead of compressing controls into tiny icons.",
      "Cards can vary in height because full recipe titles are never clipped; this preserves content integrity over masonry-perfect rows."
    ]
  },
  {
    "folder": "proposal-03",
    "id": "proposal-03",
    "name": "Precision Grid",
    "tagline": "A Swiss-modern recipe index where measurement becomes the luxury cue.",
    "thesis": "Paul's Cookbook is redesigned as a disciplined cooking reference: visible modular structure, hairline strata, clean photography, and tabular prep/price numerals that make the collection feel precise without becoming cold.",
    "palette": {
      "light": {
        "paper": "#f5f5f1",
        "paper2": "#ebebe5",
        "ink": "#111318",
        "muted": "#555d68",
        "line": "rgba(17, 19, 24, 0.18)",
        "accent": "#164cff"
      },
      "dark": {
        "paper": "#0e1117",
        "paper2": "#171b22",
        "ink": "#f4f6f8",
        "muted": "#a7b0bd",
        "line": "rgba(244, 246, 248, 0.20)",
        "accent": "#78a0ff"
      }
    },
    "typography": {
      "display": "DIN Condensed / Arial Narrow / Aptos Display for a Swiss annual headline cadence without external font dependencies",
      "ui": "Aptos / Helvetica Neue / Arial / system UI for precise bilingual controls",
      "data": "JetBrains Mono/SFMono/Consolas for tabular minutes, counts, and RON values",
      "scale": "16px body minimum, 20px+ section heads, 13px+ metadata, large mode at 112.5%"
    },
    "moves": [
      "Exactly two recipe columns through 640px, then denser 3/4-column reference grids above.",
      "Category sections are indexed strata: rule, 01-08 numeral, label, and right-aligned live count.",
      "Recipe cards remove overlays and shadows; photography is a plain rectangle and the data line carries status.",
      "Prep minutes and price per serving are aligned mono numerals with quiet units and explicit partial/unavailable states.",
      "The control strip behaves like an instrument panel with count, active filters, grouping, and field+direction sort state.",
      "The drawer preserves filters, categories, more links, and preferences as a numbered systematic index."
    ],
    "tradeoffs": [
      "The design is intentionally austere; warmth comes from real food photography rather than decorative illustration.",
      "Four columns on desktop prioritize reference scanning over large editorial imagery.",
      "No webfont dependency is used, so the concept degrades through local serif/sans/mono stacks."
    ]
  }
];
