// Regenerates proposals.js from each proposal folder's meta.json plus its screenshots.
// Run from the repo root: node mocks/homepage-four-proposals/build-gallery.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const IMG = /\.(jpe?g|png|webp)$/i;
const walk = d => fs.existsSync(d)
  ? fs.readdirSync(d, { withFileTypes: true }).flatMap(e => e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)])
  : [];
const rel = f => path.relative(dir, f).split(path.sep).join('/');

const folders = fs.readdirSync(dir, { withFileTypes: true })
  .filter(d => d.isDirectory() && /^\d\d-/.test(d.name))
  .map(d => d.name)
  .sort();

const proposals = folders.map(folder => {
  const metaPath = path.join(dir, folder, 'meta.json');
  const meta = fs.existsSync(metaPath) ? JSON.parse(fs.readFileSync(metaPath, 'utf8')) : { name: folder };
  const screens = walk(path.join(dir, folder, 'screens')).filter(f => IMG.test(f)).map(rel).sort();
  const compare = Object.fromEntries(walk(path.join(dir, folder, 'compare')).filter(f => IMG.test(f)).map(f => [path.basename(f).replace(IMG, ''), rel(f)]));
  return { folder, ...meta, screens, compare };
});

const baseline = Object.fromEntries(walk(path.join(dir, 'baseline', 'compare')).filter(f => IMG.test(f)).map(f => [path.basename(f).replace(IMG, ''), rel(f)]));

fs.writeFileSync(
  path.join(dir, 'proposals.js'),
  `/* Generated by build-gallery.mjs — do not edit by hand. */\nwindow.BASELINE = ${JSON.stringify(baseline, null, 1)};\nwindow.PROPOSALS = ${JSON.stringify(proposals, null, 1)};\n`
);
console.log(proposals.map(p => `${p.folder}: ${p.name} (${p.screens.length} screens, ${Object.keys(p.compare).length} compare states)`).join('\n'));
console.log(`baseline: ${Object.keys(baseline).length} compare states`);
