/* Generated by build-gallery.mjs — do not edit by hand. */
window.BASELINE = {
 "d-dark": "baseline/compare/d-dark.webp",
 "d-full": "baseline/compare/d-full.webp",
 "d-light": "baseline/compare/d-light.webp",
 "m-dark": "baseline/compare/m-dark.webp",
 "m-full": "baseline/compare/m-full.webp",
 "m-large-en": "baseline/compare/m-large-en.webp",
 "m-light": "baseline/compare/m-light.webp",
 "m-menu": "baseline/compare/m-menu.webp",
 "m-scroll": "baseline/compare/m-scroll.webp"
};
window.PROPOSALS = [
 {
  "folder": "01-market-grid",
  "name": "Market Grid",
  "tagline": "Swiss typographic grid meets the market shelf label: square photos lead, and minutes and lei are set like a well-made price tag.",
  "thesis": "A strict modular grid, flat edges and one grotesque family set in three widths give the cookbook a calm, precise studio-brand look. What only this site knows, the cost per serving and the prep time, becomes the typographic hero of every card: condensed tabular numerals, raised decimals, and an ultramarine price tag. One ultramarine owns the house (top bar, masthead, footer) and the price, black marks the reader's own selections, and everything else stays paper and ink so the food photos stay dominant.",
  "fonts": [
   "Archivo Expanded (wdth 125) / Condensed (wdth 75) — wordmark, headings and the tabular price/time numerals",
   "Archivo Normal (wdth 100) — body text, controls, card titles"
  ],
  "palette": [
   {
    "name": "Ultramarine",
    "hex": "#2B3CD8",
    "role": "Brand territory: top bar, masthead, footer, drawer header and every price tag"
   },
   {
    "name": "Ink",
    "hex": "#111216",
    "role": "Text, section rules and selected states (sort, filters, toggles)"
   },
   {
    "name": "Paper",
    "hex": "#FAFAF9",
    "role": "Light page ground"
   },
   {
    "name": "Graphite",
    "hex": "#53565F",
    "role": "Secondary text and units (min, lei)"
   },
   {
    "name": "Night",
    "hex": "#0E0F12",
    "role": "Dark theme ground; ink flips to #EDEDEF"
   },
   {
    "name": "Periwinkle",
    "hex": "#D3D8FF",
    "role": "Secondary text on ultramarine"
   }
  ],
  "highlights": [
   "Every card gets a shelf label: a two-line title slot, then a ruled row with minutes on the left and a blue price tag on the right, with raised decimals and 'lei' underneath. Partial estimates get a small '+' ('at least') plus a tooltip and a screen-reader label.",
   "Desktop gives the masthead to a large dish of the day that answers the 'Ce gătim azi?' question. From 1180px each category heading becomes a sticky column beside a 3-column photo grid; the flat list uses 4 columns.",
   "Sorting and grouping reflow the cards with a FLIP animation (the page's one motion moment; turned off under reduced-motion), and the sort arrow rotates to show direction.",
   "Filtered state is always visible: the count shows '12/33', removable black filter pills plus a clear-all action, a badge on the menu button, and filter chips in the drawer that show how many recipes each keyword would leave (chips that would leave none are disabled).",
   "The drawer has sticky 'N rețete ↓' results at the bottom, focus trapping with inert page content, Escape/backdrop close, scroll lock, and radio-group preferences (RO/EN, light/dark, normal/large at 118.75% root scale)."
  ],
  "tradeoffs": [
   "The square card crop cuts the sides of the 3:2 photos; production would want per-image focal points or 4:3 thumbs.",
   "FLIP reordering needs keyed, persistent card nodes; in React that means stable keys plus a small layout-animation hook (or Framer Motion), not a plain re-render.",
   "Blue tags on all 33 cards make a strong repeating pattern. If the owner finds it too loud, the fallback is ink numerals with blue kept only for the masthead."
  ],
  "screens": [
   "01-market-grid/screens/x-360-en-large.webp",
   "01-market-grid/screens/x-desktop-dark-en.webp",
   "01-market-grid/screens/x-desktop-dark-flat-time.webp",
   "01-market-grid/screens/x-desktop-jump.webp",
   "01-market-grid/screens/x-desktop-menu.webp",
   "01-market-grid/screens/x-mobile-dark-large-menu.webp",
   "01-market-grid/screens/x-mobile-dark-large.webp",
   "01-market-grid/screens/x-mobile-empty.webp",
   "01-market-grid/screens/x-mobile-filtered-price-desc.webp",
   "01-market-grid/screens/x-mobile-menu-filter.webp",
   "01-market-grid/screens/x-tablet.webp"
  ],
  "compare": {
   "d-dark": "01-market-grid/compare/d-dark.webp",
   "d-full": "01-market-grid/compare/d-full.webp",
   "d-light": "01-market-grid/compare/d-light.webp",
   "m-dark": "01-market-grid/compare/m-dark.webp",
   "m-full": "01-market-grid/compare/m-full.webp",
   "m-large-en": "01-market-grid/compare/m-large-en.webp",
   "m-light": "01-market-grid/compare/m-light.webp",
   "m-menu": "01-market-grid/compare/m-menu.webp",
   "m-scroll": "01-market-grid/compare/m-scroll.webp"
  }
 },
 {
  "folder": "02-evening-kitchen",
  "name": "The Evening Kitchen",
  "tagline": "The cookbook as a table lit by one pendant lamp after work: dishes glow out of a deep aubergine room, and Daylight turns the lamp into sun through a kitchen window.",
  "thesis": "Most home cooking happens after work, in low warm light, so the page is set in that scene. Deep aubergine ground, brass accents and a soft falloff of lamp light let the real food photos glow like plates on a dark table, while Bodoni Moda headings read like a restaurant menu card. Chrome is sparse and typographic (minutes and lei, no emoji), so the page stays a fast 'what do I cook tonight' tool with images at its centre.",
  "fonts": [
   "Bodoni Moda (optical sizes 6–96) — greeting, wordmark, section headings and dish names; the menu-card voice, and its opsz axis keeps hairlines sturdy at card-title sizes",
   "Hanken Grotesk — all UI, body and figures (tabular minutes and lei); warm grotesk that stays crisp at 15px on dark"
  ],
  "palette": [
   {
    "name": "Aubergine dusk",
    "hex": "#22171d",
    "role": "Dark ground (the table after sundown)"
   },
   {
    "name": "Walnut shadow",
    "hex": "#1a1116",
    "role": "Dark drawer and footer, one step deeper"
   },
   {
    "name": "Linen",
    "hex": "#f3e9df",
    "role": "Dark-theme text and active controls"
   },
   {
    "name": "Brass",
    "hex": "#d9ad6a",
    "role": "Dark accent: prices, switch, selected chips, the lamp glow"
   },
   {
    "name": "Sage plaster",
    "hex": "#e9eae2",
    "role": "Daylight ground (kitchen wall at noon)"
   },
   {
    "name": "Aubergine ink",
    "hex": "#2b1b24",
    "role": "Daylight text and active controls"
   },
   {
    "name": "Bronze",
    "hex": "#7a5522",
    "role": "Daylight accent (AA on plaster)"
   }
  ],
  "highlights": [
   "Signature: the category rail at the top of the page carries the lamp. The section you are scrolling through is the lit pill; it glides between categories using a clip-path, and in Daylight it becomes a solid ink tab",
   "Light itself changes between themes: a warm pendant-lamp pool at dusk and blurred window panes by day. Photos get a soft vignette at night and none in Daylight, so the light theme is designed as its own counterpart rather than a colour inversion",
   "Cards are frameless 4:5 plates with a Bodoni title and one typographic meta line ('30 min · ≈ 2,04 lei'). '≈' marks a partial estimate, '—' shows when there is no price, and screen readers get the full cost label. On sort/filter changes the plates fade up from dim, as if the lights were coming on",
   "Active filters are visible on the page as removable chips, with a count badge on both the Filters and menu buttons. The drawer adds a live 'Show N recipes' button, category rows with round plate thumbnails, and focus trap, inert page, Escape, backdrop close and scroll lock",
   "Today's pick shows one real recipe, chosen by date, as a large lit plate beside the greeting. It hides while you search or filter so results start at the top. Search ignores diacritics, so 'ciorba' finds 'ciorbă'"
  ],
  "tradeoffs": [
   "Bodoni Moda is a high-contrast face. It holds up here because of optical sizing, but Tailwind needs font-variation settings and the variable font file is heavier than a single static cut",
   "The 480px square webp thumbs look soft in the 4-column desktop grid on 2x screens. Production should generate 800px thumbs or add a srcset",
   "The sticky rail and lamp light need scroll tracking and an extra layer of CSS; the React port needs an IntersectionObserver hook and must be tuned carefully so nothing jitters"
  ],
  "screens": [
   "02-evening-kitchen/screens/dark-desktop-flat-price-desc.webp",
   "02-evening-kitchen/screens/dark-desktop-jump.webp",
   "02-evening-kitchen/screens/dark-desktop-menu.webp",
   "02-evening-kitchen/screens/dark-mobile-scrolled.webp",
   "02-evening-kitchen/screens/dark-tablet.webp",
   "02-evening-kitchen/screens/en-360-empty.webp",
   "02-evening-kitchen/screens/en-360-filtered.webp",
   "02-evening-kitchen/screens/en-360-filters-drawer.webp",
   "02-evening-kitchen/screens/en-360.webp",
   "02-evening-kitchen/screens/large-mobile-scrolled.webp",
   "02-evening-kitchen/screens/large-mobile.webp",
   "02-evening-kitchen/screens/light-desktop.webp",
   "02-evening-kitchen/screens/light-large-en-menu.webp",
   "02-evening-kitchen/screens/light-mobile-menu.webp",
   "02-evening-kitchen/screens/light-mobile-scrolled.webp",
   "02-evening-kitchen/screens/light-mobile.webp"
  ],
  "compare": {
   "d-dark": "02-evening-kitchen/compare/d-dark.webp",
   "d-full": "02-evening-kitchen/compare/d-full.webp",
   "d-light": "02-evening-kitchen/compare/d-light.webp",
   "m-dark": "02-evening-kitchen/compare/m-dark.webp",
   "m-full": "02-evening-kitchen/compare/m-full.webp",
   "m-large-en": "02-evening-kitchen/compare/m-large-en.webp",
   "m-light": "02-evening-kitchen/compare/m-light.webp",
   "m-menu": "02-evening-kitchen/compare/m-menu.webp",
   "m-scroll": "02-evening-kitchen/compare/m-scroll.webp"
  }
 },
 {
  "folder": "03-enamel-pantry",
  "name": "Enamel Pantry",
  "tagline": "Each of the eight categories gets its own enamel glaze, and those colours are how you get around the page.",
  "thesis": "The homepage is set up like a tidy Romanian pantry. Categories sit on glazed tiles tinted in their own colour, and a shelf of photo 'lids' with coloured rims gets you to any section in one tap. The geometry is soft and flat, with no shadows, and the colour frames the food photos instead of competing with them. A long page of 33 recipes becomes quick to scan: you learn the palette once and always know where you are.",
  "fonts": [
   "Gabarito — display: greeting, section names, counts, wordmark; round bowls and flat terminals like enamel labels",
   "Figtree — text: titles, metadata, controls; open apertures, legible at 15–17px, full Romanian diacritics"
  ],
  "palette": [
   {
    "name": "Grout",
    "hex": "#ECEEEA",
    "role": "Light page ground; cool, not cream"
   },
   {
    "name": "Navy enamel",
    "hex": "#18202E",
    "role": "Ink, active controls, footer tile (the classic mug rim)"
   },
   {
    "name": "Cast iron",
    "hex": "#0F131B",
    "role": "Dark page ground"
   },
   {
    "name": "Yolk",
    "hex": "#F4B93C",
    "role": "Mic Dejun / Breakfast"
   },
   {
    "name": "Tomato",
    "hex": "#CE3F26",
    "role": "Paste / Pasta"
   },
   {
    "name": "Jade",
    "hex": "#0F7F5C",
    "role": "Stir-Fry"
   },
   {
    "name": "Cobalt",
    "hex": "#305EB7",
    "role": "Supe și Tocane / Soups & Stews"
   },
   {
    "name": "Plum",
    "hex": "#7F3A72",
    "role": "Feluri Principale / Main Courses"
   },
   {
    "name": "Rose",
    "hex": "#E48396",
    "role": "Burgeri și Wrap-uri / Burgers & Wraps"
   },
   {
    "name": "Leaf",
    "hex": "#91BB54",
    "role": "Salate și Gustări / Salads & Bites"
   },
   {
    "name": "Duck egg",
    "hex": "#72BED1",
    "role": "Baze de Gătit / Basics"
   }
  ],
  "highlights": [
   "Colour is the navigation system: section tiles, count badges, the header rim, the active item in the desktop rail and the mobile index all share each category's glaze",
   "Mobile: a shelf of photo 'lids' at the top, then a floating pill that shows the current section in its colour and opens a 2×4 grid of glaze tiles for jumping between categories",
   "Desktop: a sticky vertical rail of the same lids, with the active category filled in its glaze, next to a 3–4 column grid",
   "Cost per serving is set with care: tabular numbers, a '≈' marker plus accessible label for partial estimates, '—' when there's no price, and the active sort field is emphasised on every card",
   "Sort, filter and grouping changes animate cards in place with View Transitions (skipped under reduced motion); on mobile the search row folds into an icon once you scroll"
  ],
  "tradeoffs": [
   "Eight hues need ongoing discipline. Every new category or theme has to be checked for contrast, and the text colour on each glaze (white or ink) is set per colour",
   "Relies on modern CSS (oklch, color-mix, View Transitions). The Tailwind port needs these as theme tokens, with fallbacks for older Safari",
   "On desktop, categories with only one or two recipes leave a partly empty tile"
  ],
  "screens": [
   "03-enamel-pantry/screens/x-dark-mobile-index.webp",
   "03-enamel-pantry/screens/x-dark-mobile-menu.webp",
   "03-enamel-pantry/screens/x-dark-mobile-scrolled.webp",
   "03-enamel-pantry/screens/x-dark-mobile.webp",
   "03-enamel-pantry/screens/x-desktop-dark-scrolled.webp",
   "03-enamel-pantry/screens/x-large-en-360-b.webp",
   "03-enamel-pantry/screens/x-large-en-360.webp",
   "03-enamel-pantry/screens/x-mobile-drawer-filters.webp",
   "03-enamel-pantry/screens/x-mobile-empty.webp",
   "03-enamel-pantry/screens/x-mobile-filtered-flat.webp",
   "03-enamel-pantry/screens/x-mobile-index.webp",
   "03-enamel-pantry/screens/x-mobile-jumped.webp",
   "03-enamel-pantry/screens/x-tablet.webp"
  ],
  "compare": {
   "d-dark": "03-enamel-pantry/compare/d-dark.webp",
   "d-full": "03-enamel-pantry/compare/d-full.webp",
   "d-light": "03-enamel-pantry/compare/d-light.webp",
   "m-dark": "03-enamel-pantry/compare/m-dark.webp",
   "m-full": "03-enamel-pantry/compare/m-full.webp",
   "m-large-en": "03-enamel-pantry/compare/m-large-en.webp",
   "m-light": "03-enamel-pantry/compare/m-light.webp",
   "m-menu": "03-enamel-pantry/compare/m-menu.webp",
   "m-scroll": "03-enamel-pantry/compare/m-scroll.webp"
  }
 },
 {
  "folder": "04-light-table",
  "name": "The Light Table",
  "tagline": "The homepage as a contact sheet on a light table: the photographs carry all the colour, the interface recedes to quiet gallery labels.",
  "thesis": "Image-first to the point of disappearance: sharp square prints (a 6x6 medium-format contact sheet that uses the 480px thumbs natively), captions set like museum wall labels (title, minutes, lei), and a neutral paper/graphite system whose only colour is a china-marker red that underlines what you chose. A daily-rotating 'today's plate' answers the greeting 'Ce gătim azi?' with a real recipe that develops like a print on load, so the page feels curated without inventing any content.",
  "fonts": [
   "Archivo (expanded width 112–125%, light 300) — wall titles: greeting, category rooms, brand wordmark",
   "Archivo (normal width, 480–650, tabular figures) — labels, controls, minutes and lei"
  ],
  "palette": [
   {
    "name": "Gallery wall",
    "hex": "#F1F1EF",
    "role": "Light background"
   },
   {
    "name": "Paper",
    "hex": "#FAFAF9",
    "role": "Light drawer surface"
   },
   {
    "name": "Graphite",
    "hex": "#17181B",
    "role": "Light ink, selected chips/segments"
   },
   {
    "name": "Pencil",
    "hex": "#50545B",
    "role": "Secondary text (~6.9:1 on wall)"
   },
   {
    "name": "Silver",
    "hex": "#B7B9BD",
    "role": "Hairlines, chip borders"
   },
   {
    "name": "Darkroom",
    "hex": "#121315",
    "role": "Dark background"
   },
   {
    "name": "Darkroom paper",
    "hex": "#1A1B1E",
    "role": "Dark drawer surface"
   },
   {
    "name": "Fixer white",
    "hex": "#EDEDEA",
    "role": "Dark ink"
   },
   {
    "name": "China marker",
    "hex": "#C4352B",
    "role": "Active sort underline and filter badge (dark: #F0675B)"
   }
  ],
  "highlights": [
   "First mobile viewport (390x844): greeting, today's plate with title/min/lei, the full control strip and the first row of prints with titles.",
   "Control strip is one sticky row down to 360px (count, category switch, Name/Time/Price with arrow + hand-drawn underline); results are filtered via the drawer and shown as removable tags on the page; the opening collapses while searching/filtering so results come first.",
   "Price is typographic, not an emoji: '≈ 2,04 lei' marks partial estimates (title + screen-reader label), '— lei' for unavailable; locale-aware decimals.",
   "Drawer with image-led category index (thumb + name + live count, empty ones disabled), AND chips, More links and RO/EN, light/dark, normal/large segmented radios; inert background, Escape/backdrop close, scroll lock, focus return.",
   "Sort/group/filter changes reorder prints with the View Transitions API (FLIP for free); reduced-motion disables all of it and the print 'develop' moment."
  ],
  "tradeoffs": [
   "Single typeface on purpose (width axis as hierarchy); needs a variable Archivo build with the wdth axis in production.",
   "The featured plate changes daily (seeded by date), so screenshots and first impressions vary; square crops of 3:2 photos may clip some plated dishes.",
   "View Transitions is Chromium/Safari-only; other browsers get instant (still correct) re-renders."
  ],
  "screens": [
   "04-light-table/screens/checks/d-dark-flat.webp",
   "04-light-table/screens/checks/d-dark-search.webp",
   "04-light-table/screens/checks/m-dark-menu.webp",
   "04-light-table/screens/checks/m-dark.webp",
   "04-light-table/screens/checks/m-empty.webp",
   "04-light-table/screens/checks/m-large-en-menu-bottom.webp",
   "04-light-table/screens/checks/m-large-en.webp",
   "04-light-table/screens/checks/s360-filtered.webp",
   "04-light-table/screens/checks/s360-menu-chips.webp",
   "04-light-table/screens/checks/s360-price-desc-scrolled.webp",
   "04-light-table/screens/checks/s360.webp",
   "04-light-table/screens/checks/t768-jump.webp",
   "04-light-table/screens/checks/t768.webp"
  ],
  "compare": {
   "d-dark": "04-light-table/compare/d-dark.webp",
   "d-full": "04-light-table/compare/d-full.webp",
   "d-light": "04-light-table/compare/d-light.webp",
   "m-dark": "04-light-table/compare/m-dark.webp",
   "m-full": "04-light-table/compare/m-full.webp",
   "m-large-en": "04-light-table/compare/m-large-en.webp",
   "m-light": "04-light-table/compare/m-light.webp",
   "m-menu": "04-light-table/compare/m-menu.webp",
   "m-scroll": "04-light-table/compare/m-scroll.webp"
  }
 }
];
