/**
 * Collects each proposal's concept.json into concepts.js so the compare page
 * works from the file system without fetch().
 *
 * Run from the repo root:  node mocks/homepage-v2/shared/assemble.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const shared = path.dirname(fileURLToPath(import.meta.url));
const suite = path.resolve(shared, '..');

const concepts = fs
  .readdirSync(suite)
  .filter(name => name.startsWith('proposal-'))
  .sort()
  .map(folder => {
    const file = path.join(suite, folder, 'concept.json');
    if (!fs.existsSync(file)) return null;
    return { folder, ...JSON.parse(fs.readFileSync(file, 'utf8').replace(/^\uFEFF/, '')) };
  })
  .filter(Boolean);

fs.writeFileSync(
  path.join(suite, 'concepts.js'),
  `/* Generated by shared/assemble.mjs - do not edit by hand. */\nwindow.COOKBOOK_CONCEPTS = ${JSON.stringify(concepts, null, 2)};\n`,
  'utf8'
);
console.log(`Assembled ${concepts.length} concepts.`);
