/* Generated by prepare.mjs - do not edit by hand. */
window.COOKBOOK_DATA = {
  "brand": "Paul's Cookbook",
  "recipeCount": 33,
  "categories": [
    {
      "id": "breakfast",
      "folder": "breakfast",
      "name": {
        "ro": "Mic Dejun",
        "en": "Breakfast"
      }
    },
    {
      "id": "pasta",
      "folder": "pasta",
      "name": {
        "ro": "Paste",
        "en": "Pasta"
      }
    },
    {
      "id": "stir-fries",
      "folder": "stir-fries",
      "name": {
        "ro": "Stir-Fry",
        "en": "Stir-Fries"
      }
    },
    {
      "id": "soups-and-stews",
      "folder": "soups-and-stews",
      "name": {
        "ro": "Supe și Tocane",
        "en": "Soups & Stews"
      }
    },
    {
      "id": "main-courses",
      "folder": "main-courses",
      "name": {
        "ro": "Feluri Principale",
        "en": "Main Courses"
      }
    },
    {
      "id": "burgers-and-wraps",
      "folder": "burgers-and-wraps",
      "name": {
        "ro": "Burgeri și Wrap-uri",
        "en": "Burgers & Wraps"
      }
    },
    {
      "id": "salads-and-bites",
      "folder": "salads-and-bites",
      "name": {
        "ro": "Salate și Gustări",
        "en": "Salads & Bites"
      }
    },
    {
      "id": "basics",
      "folder": "basics",
      "name": {
        "ro": "Baze de Gătit",
        "en": "Basics"
      }
    }
  ],
  "filters": [
    {
      "id": "chicken",
      "type": "meatType",
      "label": {
        "ro": "Pui",
        "en": "Chicken"
      }
    },
    {
      "id": "beef",
      "type": "meatType",
      "label": {
        "ro": "Vită",
        "en": "Beef"
      }
    },
    {
      "id": "fish",
      "type": "meatType",
      "label": {
        "ro": "Pește",
        "en": "Fish"
      }
    },
    {
      "id": "vegetarian",
      "type": "meatType",
      "label": {
        "ro": "Vegetarian",
        "en": "Vegetarian"
      }
    },
    {
      "id": "oven-baked",
      "type": "cookType",
      "label": {
        "ro": "La Cuptor",
        "en": "Oven-Baked"
      }
    },
    {
      "id": "pan-fry",
      "type": "cookType",
      "label": {
        "ro": "Prăjit la Tigaie",
        "en": "Pan-Fry"
      }
    },
    {
      "id": "boiling",
      "type": "cookType",
      "label": {
        "ro": "Fiert",
        "en": "Boiling"
      }
    },
    {
      "id": "no-cook",
      "type": "cookType",
      "label": {
        "ro": "Fără Gătit",
        "en": "No-Cook"
      }
    },
    {
      "id": "garlic",
      "type": "ingredient",
      "label": {
        "ro": "Usturoi",
        "en": "Garlic"
      }
    },
    {
      "id": "onion",
      "type": "ingredient",
      "label": {
        "ro": "Ceapă",
        "en": "Onion"
      }
    },
    {
      "id": "tomatoes",
      "type": "ingredient",
      "label": {
        "ro": "Roșii",
        "en": "Tomatoes"
      }
    },
    {
      "id": "eggs",
      "type": "ingredient",
      "label": {
        "ro": "Ouă",
        "en": "Eggs"
      }
    },
    {
      "id": "carrots",
      "type": "ingredient",
      "label": {
        "ro": "Morcovi",
        "en": "Carrots"
      }
    },
    {
      "id": "green-onion",
      "type": "ingredient",
      "label": {
        "ro": "Ceapă Verde",
        "en": "Green Onion"
      }
    },
    {
      "id": "butter",
      "type": "ingredient",
      "label": {
        "ro": "Unt",
        "en": "Butter"
      }
    },
    {
      "id": "pasta",
      "type": "ingredient",
      "label": {
        "ro": "Paste",
        "en": "Pasta"
      }
    },
    {
      "id": "peppers",
      "type": "ingredient",
      "label": {
        "ro": "Ardei",
        "en": "Peppers"
      }
    },
    {
      "id": "parmesan",
      "type": "ingredient",
      "label": {
        "ro": "Parmezan",
        "en": "Parmesan"
      }
    },
    {
      "id": "potatoes",
      "type": "ingredient",
      "label": {
        "ro": "Cartofi",
        "en": "Potatoes"
      }
    },
    {
      "id": "rice",
      "type": "ingredient",
      "label": {
        "ro": "Orez",
        "en": "Rice"
      }
    }
  ],
  "recipes": [
    {
      "id": "frittata",
      "title": {
        "ro": "Frittata",
        "en": "Frittata"
      },
      "category": "breakfast",
      "minutes": 30,
      "servings": 4,
      "effort": "easy",
      "keywords": [
        "easy",
        "vegetarian",
        "pan-fry",
        "onion",
        "tomatoes",
        "eggs"
      ],
      "ingredientCount": 9,
      "stepCount": 7,
      "price": 2.04,
      "priceStatus": "partial",
      "unpricedCount": 1,
      "image": "public/images/recipes/breakfast/frittata.thumb.webp",
      "imageFull": "public/images/recipes/breakfast/frittata.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "tropical-yogurt-parfaits",
      "title": {
        "ro": "Parfaituri cu Iaurt Tropical",
        "en": "Tropical Yogurt Parfaits"
      },
      "category": "breakfast",
      "minutes": 20,
      "servings": 6,
      "effort": "easy",
      "keywords": [
        "easy",
        "vegetarian",
        "no-cook"
      ],
      "ingredientCount": 6,
      "stepCount": 4,
      "price": 2.67,
      "priceStatus": "partial",
      "unpricedCount": 2,
      "image": "public/images/recipes/breakfast/tropical-yogurt-parfaits.thumb.webp",
      "imageFull": "public/images/recipes/breakfast/tropical-yogurt-parfaits.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "ground-beef-tomato-pasta",
      "title": {
        "ro": "Paste cu Carne de Vită și Sos de Roșii",
        "en": "Ground Beef Tomato Pasta"
      },
      "category": "pasta",
      "minutes": 45,
      "servings": 3,
      "effort": "easy",
      "keywords": [
        "easy",
        "beef",
        "boiling",
        "garlic",
        "onion",
        "tomatoes",
        "carrots",
        "pasta",
        "parmesan"
      ],
      "ingredientCount": 14,
      "stepCount": 7,
      "price": 5.43,
      "priceStatus": "partial",
      "unpricedCount": 1,
      "image": "public/images/recipes/pasta/ground-beef-tomato-pasta.thumb.webp",
      "imageFull": "public/images/recipes/pasta/ground-beef-tomato-pasta.jpg",
      "dateAdded": "2026-03-08"
    },
    {
      "id": "macaroane-cu-varza-calita",
      "title": {
        "ro": "Macaroane cu varză călită",
        "en": "Pasta with Braised Cabbage"
      },
      "category": "pasta",
      "minutes": 70,
      "servings": 4,
      "effort": "medium",
      "keywords": [
        "cabbage",
        "vegetarian",
        "traditional",
        "boiling",
        "onion",
        "pasta"
      ],
      "ingredientCount": 6,
      "stepCount": 10,
      "price": 2.45,
      "priceStatus": "complete",
      "unpricedCount": 0,
      "image": "public/images/recipes/pasta/macaroane-cu-varza-calita.thumb.webp",
      "imageFull": "public/images/recipes/pasta/macaroane-cu-varza-calita.jpg",
      "dateAdded": "2026-07-18"
    },
    {
      "id": "marry-me-chicken-pasta",
      "title": {
        "ro": "Paste cu Pui Marry Me",
        "en": "Marry Me Chicken Pasta"
      },
      "category": "pasta",
      "minutes": 30,
      "servings": 5,
      "effort": "medium",
      "keywords": [
        "medium",
        "chicken",
        "pan-fry",
        "garlic",
        "onion",
        "tomatoes",
        "butter",
        "pasta",
        "parmesan"
      ],
      "ingredientCount": 16,
      "stepCount": 8,
      "price": 5.95,
      "priceStatus": "complete",
      "unpricedCount": 0,
      "image": "public/images/recipes/pasta/marry-me-chicken-pasta.thumb.webp",
      "imageFull": "public/images/recipes/pasta/marry-me-chicken-pasta.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "shrimp-alfredo",
      "title": {
        "ro": "Paste Alfredo cu Creveți",
        "en": "Shrimp Alfredo"
      },
      "category": "pasta",
      "minutes": 30,
      "servings": 3,
      "effort": "medium",
      "keywords": [
        "medium",
        "fish",
        "pan-fry",
        "boiling",
        "garlic",
        "butter",
        "pasta",
        "parmesan"
      ],
      "ingredientCount": 9,
      "stepCount": 7,
      "price": 6.01,
      "priceStatus": "complete",
      "unpricedCount": 0,
      "image": "public/images/recipes/pasta/shrimp-alfredo.thumb.webp",
      "imageFull": "public/images/recipes/pasta/shrimp-alfredo.jpg",
      "dateAdded": "2026-03-08"
    },
    {
      "id": "tomato-marinara-pasta",
      "title": {
        "ro": "Paste cu Sos Marinara de Roșii Proaspete",
        "en": "Fresh Tomato Marinara Pasta"
      },
      "category": "pasta",
      "minutes": 20,
      "servings": 3,
      "effort": "easy",
      "keywords": [
        "easy",
        "vegetarian",
        "boiling",
        "garlic",
        "onion",
        "tomatoes",
        "pasta",
        "parmesan"
      ],
      "ingredientCount": 10,
      "stepCount": 7,
      "price": 3.66,
      "priceStatus": "partial",
      "unpricedCount": 2,
      "image": "public/images/recipes/pasta/tomato-marinara-pasta.thumb.webp",
      "imageFull": "public/images/recipes/pasta/tomato-marinara-pasta.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "bacon-cabbage-fried-rice",
      "title": {
        "ro": "Orez Prăjit cu Bacon și Varză",
        "en": "Bacon and Cabbage Fried Rice"
      },
      "category": "stir-fries",
      "minutes": 30,
      "servings": 4,
      "effort": "medium",
      "keywords": [
        "medium",
        "pan-fry",
        "bacon",
        "garlic",
        "eggs",
        "green-onion",
        "rice"
      ],
      "ingredientCount": 15,
      "stepCount": 10,
      "price": 2.8,
      "priceStatus": "partial",
      "unpricedCount": 2,
      "image": "public/images/recipes/stir-fries/bacon-cabbage-fried-rice.thumb.webp",
      "imageFull": "public/images/recipes/stir-fries/bacon-cabbage-fried-rice.jpg",
      "dateAdded": "2026-01-12"
    },
    {
      "id": "chicken-onion-stir-fry",
      "title": {
        "ro": "Pui cu Ceapă la Tigaie",
        "en": "Chicken and Onion Stir Fry"
      },
      "category": "stir-fries",
      "minutes": 30,
      "servings": 4,
      "effort": "medium",
      "keywords": [
        "medium",
        "chicken",
        "pan-fry",
        "garlic",
        "onion",
        "green-onion",
        "peppers"
      ],
      "ingredientCount": 24,
      "stepCount": 8,
      "price": 4.66,
      "priceStatus": "complete",
      "unpricedCount": 0,
      "image": "public/images/recipes/stir-fries/chicken-onion-stir-fry.thumb.webp",
      "imageFull": "public/images/recipes/stir-fries/chicken-onion-stir-fry.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "chinese-stir-fried-noodles",
      "title": {
        "ro": "Tăiței Chinezești Prăjiți",
        "en": "Chinese Stir Fried Noodles"
      },
      "category": "stir-fries",
      "minutes": 30,
      "servings": 3,
      "effort": "medium",
      "keywords": [
        "medium",
        "pan-fry",
        "noodles",
        "broccoli",
        "garlic",
        "onion",
        "carrots",
        "pasta"
      ],
      "ingredientCount": 18,
      "stepCount": 7,
      "price": 5.26,
      "priceStatus": "partial",
      "unpricedCount": 1,
      "image": "public/images/recipes/stir-fries/chinese-stir-fried-noodles.thumb.webp",
      "imageFull": "public/images/recipes/stir-fries/chinese-stir-fried-noodles.jpg",
      "dateAdded": "2026-01-22"
    },
    {
      "id": "egg-fried-rice",
      "title": {
        "ro": "Orez Prăjit cu Ou",
        "en": "Egg Fried Rice"
      },
      "category": "stir-fries",
      "minutes": 20,
      "servings": 2,
      "effort": "easy",
      "keywords": [
        "easy",
        "vegetarian",
        "pan-fry",
        "garlic",
        "onion",
        "eggs",
        "carrots",
        "green-onion",
        "rice"
      ],
      "ingredientCount": 12,
      "stepCount": 6,
      "price": 2.76,
      "priceStatus": "partial",
      "unpricedCount": 2,
      "image": "public/images/recipes/stir-fries/egg-fried-rice.thumb.webp",
      "imageFull": "public/images/recipes/stir-fries/egg-fried-rice.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "ground-beef-and-potato-stir-fry",
      "title": {
        "ro": "Carne Tocată de Vită cu Cartofi la Wok",
        "en": "Ground Beef and Potato Stir-Fry"
      },
      "category": "stir-fries",
      "minutes": 35,
      "servings": 3,
      "effort": "medium",
      "keywords": [
        "medium",
        "beef",
        "pan-fry",
        "garlic",
        "green-onion",
        "peppers",
        "potatoes"
      ],
      "ingredientCount": 16,
      "stepCount": 8,
      "price": 6.55,
      "priceStatus": "partial",
      "unpricedCount": 2,
      "image": "public/images/recipes/stir-fries/ground-beef-and-potato-stir-fry.thumb.webp",
      "imageFull": "public/images/recipes/stir-fries/ground-beef-and-potato-stir-fry.jpg",
      "dateAdded": "2026-01-04"
    },
    {
      "id": "butter-chicken",
      "title": {
        "ro": "Pui cu Unt",
        "en": "Butter Chicken"
      },
      "category": "soups-and-stews",
      "minutes": 215,
      "servings": 3,
      "effort": "medium",
      "keywords": [
        "medium",
        "chicken",
        "pan-fry",
        "garlic",
        "tomatoes",
        "butter",
        "rice"
      ],
      "ingredientCount": 16,
      "stepCount": 4,
      "price": 2.64,
      "priceStatus": "partial",
      "unpricedCount": 3,
      "image": "public/images/recipes/soups-and-stews/butter-chicken.thumb.webp",
      "imageFull": "public/images/recipes/soups-and-stews/butter-chicken.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "chicken-soup",
      "title": {
        "ro": "Supă de Pui",
        "en": "Chicken Soup"
      },
      "category": "soups-and-stews",
      "minutes": 60,
      "servings": 4,
      "effort": "easy",
      "keywords": [
        "chicken",
        "broth-based",
        "boiling",
        "garlic",
        "onion",
        "carrots",
        "pasta"
      ],
      "ingredientCount": 12,
      "stepCount": 9,
      "price": 6.31,
      "priceStatus": "partial",
      "unpricedCount": 1,
      "image": "public/images/recipes/soups-and-stews/chicken-soup.thumb.webp",
      "imageFull": "public/images/recipes/soups-and-stews/chicken-soup.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "chicken-taco-bowls",
      "title": {
        "ro": "Boluri cu Pui Taco",
        "en": "Chicken Taco Bowls"
      },
      "category": "soups-and-stews",
      "minutes": 260,
      "servings": 6,
      "effort": "easy",
      "keywords": [
        "easy",
        "chicken",
        "boiling",
        "garlic",
        "green-onion",
        "rice"
      ],
      "ingredientCount": 16,
      "stepCount": 6,
      "price": 6.03,
      "priceStatus": "partial",
      "unpricedCount": 1,
      "image": "public/images/recipes/soups-and-stews/chicken-taco-bowls.thumb.webp",
      "imageFull": "public/images/recipes/soups-and-stews/chicken-taco-bowls.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "chickpea-beef-shawarma-soup",
      "title": {
        "ro": "Supă de Vită și Năut în Stil Shawarma",
        "en": "Chickpea Beef Shawarma Soup"
      },
      "category": "soups-and-stews",
      "minutes": 35,
      "servings": 4,
      "effort": "easy",
      "keywords": [
        "easy",
        "beef",
        "boiling",
        "garlic",
        "onion",
        "tomatoes",
        "carrots"
      ],
      "ingredientCount": 22,
      "stepCount": 7,
      "price": 8.05,
      "priceStatus": "partial",
      "unpricedCount": 3,
      "image": "public/images/recipes/soups-and-stews/chickpea-beef-shawarma-soup.thumb.webp",
      "imageFull": "public/images/recipes/soups-and-stews/chickpea-beef-shawarma-soup.jpg",
      "dateAdded": "2026-03-08"
    },
    {
      "id": "ciorba-de-varza",
      "title": {
        "ro": "Ciorbă de Varză",
        "en": "Cabbage Soup"
      },
      "category": "soups-and-stews",
      "minutes": 80,
      "servings": 6,
      "effort": "medium",
      "keywords": [
        "cabbage",
        "broth-based",
        "boiling",
        "medium",
        "traditional",
        "sausage",
        "onion",
        "eggs",
        "peppers"
      ],
      "ingredientCount": 16,
      "stepCount": 15,
      "price": 3.12,
      "priceStatus": "partial",
      "unpricedCount": 3,
      "image": "public/images/recipes/soups-and-stews/ciorba-de-varza.thumb.webp",
      "imageFull": "public/images/recipes/soups-and-stews/ciorba-de-varza.jpg",
      "dateAdded": "2026-01-26"
    },
    {
      "id": "hungarian-goulash",
      "title": {
        "ro": "Gulaș Unguresc",
        "en": "Hungarian Goulash"
      },
      "category": "soups-and-stews",
      "minutes": 140,
      "servings": 5,
      "effort": "medium",
      "keywords": [
        "medium",
        "beef",
        "boiling",
        "garlic",
        "onion",
        "tomatoes",
        "carrots",
        "butter",
        "peppers",
        "potatoes"
      ],
      "ingredientCount": 14,
      "stepCount": 8,
      "price": 8.77,
      "priceStatus": "partial",
      "unpricedCount": 2,
      "image": "public/images/recipes/soups-and-stews/hungarian-goulash.thumb.webp",
      "imageFull": "public/images/recipes/soups-and-stews/hungarian-goulash.jpg",
      "dateAdded": "2025-11-25"
    },
    {
      "id": "papricas-de-pui-cu-galuste",
      "title": {
        "ro": "Papricaș de Pui cu Găluște",
        "en": "Chicken Paprikash with Dumplings"
      },
      "category": "soups-and-stews",
      "minutes": 50,
      "servings": 4,
      "effort": "medium",
      "keywords": [
        "chicken",
        "medium",
        "boiling",
        "onion",
        "eggs",
        "carrots",
        "peppers"
      ],
      "ingredientCount": 16,
      "stepCount": 8,
      "price": 6.99,
      "priceStatus": "partial",
      "unpricedCount": 4,
      "image": "public/images/recipes/soups-and-stews/papricas-de-pui-cu-galuste.thumb.webp",
      "imageFull": "public/images/recipes/soups-and-stews/papricas-de-pui-cu-galuste.jpg",
      "dateAdded": "2026-01-15"
    },
    {
      "id": "potato-soup",
      "title": {
        "ro": "Supă de Cartofi",
        "en": "Potato Soup"
      },
      "category": "soups-and-stews",
      "minutes": 30,
      "servings": 6,
      "effort": "easy",
      "keywords": [
        "easy",
        "boiling",
        "onion",
        "eggs",
        "carrots",
        "potatoes"
      ],
      "ingredientCount": 11,
      "stepCount": 6,
      "price": 2.04,
      "priceStatus": "partial",
      "unpricedCount": 1,
      "image": "public/images/recipes/soups-and-stews/potato-soup.thumb.webp",
      "imageFull": "public/images/recipes/soups-and-stews/potato-soup.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "baked-fish-on-potato",
      "title": {
        "ro": "Pește la Cuptor pe Gratin de Cartofi",
        "en": "Baked Fish on Potato Gratin"
      },
      "category": "main-courses",
      "minutes": 70,
      "servings": 4,
      "effort": "medium",
      "keywords": [
        "medium",
        "fish",
        "oven-baked",
        "garlic",
        "butter",
        "parmesan",
        "potatoes"
      ],
      "ingredientCount": 17,
      "stepCount": 11,
      "price": 8.55,
      "priceStatus": "partial",
      "unpricedCount": 2,
      "image": "public/images/recipes/main-courses/baked-fish-on-potato.thumb.webp",
      "imageFull": "public/images/recipes/main-courses/baked-fish-on-potato.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "placinta-creata-cu-telemea",
      "title": {
        "ro": "Plăcintă creață cu telemea",
        "en": "Crinkled Telemea Cheese Pie"
      },
      "category": "main-courses",
      "minutes": 110,
      "servings": 15,
      "effort": "medium",
      "keywords": [
        "medium",
        "vegetarian",
        "oven-baked",
        "eggs",
        "butter"
      ],
      "ingredientCount": 14,
      "stepCount": 10,
      "price": 2.62,
      "priceStatus": "partial",
      "unpricedCount": 2,
      "image": "public/images/recipes/main-courses/placinta-creata-cu-telemea.thumb.webp",
      "imageFull": "public/images/recipes/main-courses/placinta-creata-cu-telemea.jpg",
      "dateAdded": "2026-07-11"
    },
    {
      "id": "roasted-chicken-and-potatoes",
      "title": {
        "ro": "Pui și Cartofi la Cuptor",
        "en": "Roasted Chicken and Potatoes"
      },
      "category": "main-courses",
      "minutes": 50,
      "servings": 4,
      "effort": "medium",
      "keywords": [
        "medium",
        "chicken",
        "oven-baked",
        "garlic",
        "potatoes"
      ],
      "ingredientCount": 10,
      "stepCount": 6,
      "price": 2.05,
      "priceStatus": "partial",
      "unpricedCount": 5,
      "image": "public/images/recipes/main-courses/roasted-chicken-and-potatoes.thumb.webp",
      "imageFull": "public/images/recipes/main-courses/roasted-chicken-and-potatoes.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "smashed-beef-burger",
      "title": {
        "ro": "Burger de Vită Strivit",
        "en": "Smashed Burger"
      },
      "category": "burgers-and-wraps",
      "minutes": 20,
      "servings": 2,
      "effort": "easy",
      "keywords": [
        "easy",
        "beef",
        "pan-fry",
        "onion",
        "tomatoes"
      ],
      "ingredientCount": 13,
      "stepCount": 8,
      "price": 6.67,
      "priceStatus": "partial",
      "unpricedCount": 2,
      "image": "public/images/recipes/burgers-and-wraps/smashed-beef-burger.thumb.webp",
      "imageFull": "public/images/recipes/burgers-and-wraps/smashed-beef-burger.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "iceberg-chicken-salad",
      "title": {
        "ro": "Salată cu Iceberg și Pui Rumenit",
        "en": "Iceberg and Roasted Chicken Salad"
      },
      "category": "salads-and-bites",
      "minutes": 20,
      "servings": 2,
      "effort": "easy",
      "keywords": [
        "easy",
        "chicken",
        "no-cook"
      ],
      "ingredientCount": 7,
      "stepCount": 5,
      "price": 11.11,
      "priceStatus": "partial",
      "unpricedCount": 2,
      "image": "public/images/recipes/salads-and-bites/iceberg-chicken-salad.thumb.webp",
      "imageFull": "public/images/recipes/salads-and-bites/iceberg-chicken-salad.jpg",
      "dateAdded": "2026-07-05"
    },
    {
      "id": "mexican-street-corn-salad",
      "title": {
        "ro": "Salată Mexicană de Porumb (Esquites)",
        "en": "Mexican Street Corn Salad (Esquites)"
      },
      "category": "salads-and-bites",
      "minutes": 20,
      "servings": 4,
      "effort": "easy",
      "keywords": [
        "easy",
        "vegetarian",
        "pan-fry",
        "garlic",
        "green-onion",
        "peppers",
        "parmesan"
      ],
      "ingredientCount": 12,
      "stepCount": 4,
      "price": 1.11,
      "priceStatus": "partial",
      "unpricedCount": 4,
      "image": "public/images/recipes/salads-and-bites/mexican-street-corn-salad.thumb.webp",
      "imageFull": "public/images/recipes/salads-and-bites/mexican-street-corn-salad.jpg",
      "dateAdded": "2026-01-14"
    },
    {
      "id": "power-greek-salad",
      "title": {
        "ro": "Salată Grecească Energizantă",
        "en": "Power Greek Salad"
      },
      "category": "salads-and-bites",
      "minutes": 30,
      "servings": 2,
      "effort": "easy",
      "keywords": [
        "easy",
        "chicken",
        "pan-fry",
        "onion",
        "tomatoes"
      ],
      "ingredientCount": 20,
      "stepCount": 6,
      "price": 8.36,
      "priceStatus": "complete",
      "unpricedCount": 0,
      "image": "public/images/recipes/salads-and-bites/power-greek-salad.thumb.webp",
      "imageFull": "public/images/recipes/salads-and-bites/power-greek-salad.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "prajitura-crema-la-crema",
      "title": {
        "ro": "Prăjitură Krem a la Krem",
        "en": "Krem a la Krem Cake"
      },
      "category": "salads-and-bites",
      "minutes": 180,
      "servings": 8,
      "effort": "medium",
      "keywords": [
        "medium",
        "vegetarian",
        "oven-baked",
        "eggs",
        "butter"
      ],
      "ingredientCount": 13,
      "stepCount": 8,
      "price": 5.35,
      "priceStatus": "complete",
      "unpricedCount": 0,
      "image": "public/images/recipes/salads-and-bites/prajitura-crema-la-crema.thumb.webp",
      "imageFull": "public/images/recipes/salads-and-bites/prajitura-crema-la-crema.jpg",
      "dateAdded": "2026-03-10"
    },
    {
      "id": "salmon-appetizers",
      "title": {
        "ro": "Aperitive cu Somon Afumat",
        "en": "Salmon Appetizers"
      },
      "category": "salads-and-bites",
      "minutes": 15,
      "servings": 2,
      "effort": "easy",
      "keywords": [
        "easy",
        "fish",
        "no-cook"
      ],
      "ingredientCount": 6,
      "stepCount": 4,
      "price": 22.13,
      "priceStatus": "complete",
      "unpricedCount": 0,
      "image": "public/images/recipes/salads-and-bites/salmon-appetizers.thumb.webp",
      "imageFull": "public/images/recipes/salads-and-bites/salmon-appetizers.jpg",
      "dateAdded": "2026-03-11"
    },
    {
      "id": "tuna-phili-spread",
      "title": {
        "ro": "Pastă de Ton cu Philadelphia",
        "en": "Tuna Phili Spread"
      },
      "category": "salads-and-bites",
      "minutes": 10,
      "servings": 4,
      "effort": "easy",
      "keywords": [
        "easy",
        "fish",
        "no-cook",
        "green-onion"
      ],
      "ingredientCount": 7,
      "stepCount": 4,
      "price": 3.41,
      "priceStatus": "partial",
      "unpricedCount": 1,
      "image": "public/images/recipes/salads-and-bites/tuna-phili-spread.thumb.webp",
      "imageFull": "public/images/recipes/salads-and-bites/tuna-phili-spread.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "boil-rice",
      "title": {
        "ro": "Cum să Gătești Orez Jasmine",
        "en": "How to Cook Jasmine Rice"
      },
      "category": "basics",
      "minutes": 23,
      "servings": 4,
      "effort": "easy",
      "keywords": [
        "easy",
        "vegetarian",
        "boiling",
        "rice"
      ],
      "ingredientCount": 2,
      "stepCount": 4,
      "price": 0,
      "priceStatus": "partial",
      "unpricedCount": 1,
      "image": "public/images/recipes/basics/boil-rice.thumb.webp",
      "imageFull": "public/images/recipes/basics/boil-rice.jpg",
      "dateAdded": "2025-11-17"
    },
    {
      "id": "mamaliga",
      "title": {
        "ro": "Mămăligă",
        "en": "Polenta (Romanian Cornmeal Mush)"
      },
      "category": "basics",
      "minutes": 25,
      "servings": 4,
      "effort": "easy",
      "keywords": [
        "easy",
        "vegetarian",
        "boiling"
      ],
      "ingredientCount": 3,
      "stepCount": 5,
      "price": 0.21,
      "priceStatus": "complete",
      "unpricedCount": 0,
      "image": "public/images/recipes/basics/mamaliga.thumb.webp",
      "imageFull": "public/images/recipes/basics/mamaliga.jpg",
      "dateAdded": "2026-03-08"
    },
    {
      "id": "simple-iceberg-salad",
      "title": {
        "ro": "Salată Simplă de Iceberg",
        "en": "Simple Iceberg Salad"
      },
      "category": "basics",
      "minutes": 10,
      "servings": 6,
      "effort": "easy",
      "keywords": [
        "easy",
        "vegetarian",
        "no-cook"
      ],
      "ingredientCount": 5,
      "stepCount": 6,
      "price": 0.91,
      "priceStatus": "complete",
      "unpricedCount": 0,
      "image": "public/images/recipes/basics/simple-iceberg-salad.thumb.webp",
      "imageFull": "public/images/recipes/basics/simple-iceberg-salad.jpg",
      "dateAdded": "2025-12-29"
    }
  ],
  "translations": {
    "ro": {
      "loading": "Se încarcă...",
      "home": "Acasă",
      "menu": "Meniu",
      "more": "Mai mult",
      "welcome": "Bun venit",
      "greetingTitle": "Ce gătim azi?",
      "greetingSubtitle": "fără reclame, doar rețete bune",
      "filter": "Filtrare",
      "about": "Despre",
      "cookingBasics": "Bazele Gătitului",
      "recipe": "Rețetă",
      "recipes": "Rețete",
      "allRecipes": "Toate Rețetele",
      "ingredients": "Ingrediente",
      "instructions": "Instrucțiuni",
      "nutrition": "Nutriție",
      "personalNotes": "Notițe Personale",
      "prepTime": "Timp de preparare",
      "prepTimeShort": "Preparare",
      "servings": "Porții",
      "increaseServings": "Mărește numărul de porții",
      "decreaseServings": "Micșorează numărul de porții",
      "resetChecklist": "Resetează lista",
      "checkedIngredients": "{checked} din {total} bifate",
      "estimatedCost": "Cost estimat",
      "partialEstimate": "Estimare parțială",
      "knownSubtotal": "Subtotal cunoscut",
      "recipeTotal": "Total rețetă",
      "costUnavailable": "Cost indisponibil",
      "priceUnavailable": "Indisponibil",
      "perServing": "RON / porție",
      "costForServings": "Pentru {count} porții",
      "costForOneServing": "Pentru 1 porție",
      "estimatedPerServing": "Aproximativ {price} / porție",
      "knownPerServing": "Subtotal pe porție: {price}",
      "ingredientNotPriced": "1 ingredient nu este inclus.",
      "ingredientsNotPriced": "{count} ingrediente nu sunt incluse.",
      "noIngredientsPriced": "Niciun ingredient nu are un cost disponibil.",
      "costQuantityNote": "Estimări pentru cantitățile folosite, nu pentru cumpărarea ambalajelor întregi.",
      "costAssumptions": "Vezi prețurile și ipotezele de calcul",
      "costConversionNote": "Calculul folosește prețurile de referință ale site-ului. Lingurițele și lingurile folosesc conversii aproximative; prețurile din magazine pot varia. Cantitățile fără o conversie disponibilă nu sunt incluse.",
      "missingPriceReason": "Nu există un preț de referință pentru acest ingredient.",
      "unsupportedUnitReason": "Această unitate nu poate fi convertită la unitatea prețului de referință.",
      "invalidPriceReason": "Prețul de referință lipsește sau nu este valid.",
      "invalidQuantityReason": "Cantitatea sau numărul de porții nu este valid.",
      "effortLevel": "Nivel de dificultate",
      "effortLevel.easy": "Ușor",
      "effortLevel.medium": "Mediu",
      "effortLevel.hard": "Dificil",
      "easy": "Ușor",
      "medium": "Mediu",
      "hard": "Dificil",
      "minutes": "minute",
      "language": "Limbă",
      "textSize": "Mărime text",
      "theme": "Temă",
      "preferences": "Preferințe",
      "dark": "Întunecat",
      "light": "Luminos",
      "normal": "Normal",
      "large": "Mare",
      "romanian": "Română",
      "english": "Engleză",
      "category": "Categorie",
      "categories": "Categorii",
      "filterByCategory": "Filtrare după Categorie",
      "allCategories": "Toate Categoriile",
      "filterByKeywords": "Filtrare după Cuvinte Cheie",
      "selectFilters": "Selectați Filtre",
      "clearFilters": "Șterge toate filtrele",
      "noRecipesFound": "Nu s-au găsit rețete",
      "pantryEmpty": "Cămara pare goală!",
      "pantryEmptyMessage": "Nu am găsit nicio rețetă care să corespundă filtrelor tale sau căutării.",
      "noRecipesMessage": "Nu există rețete care să corespundă criteriilor selectate.",
      "noIngredientsFound": "Nu s-au găsit ingrediente",
      "recipeNotFound": "Rețeta nu a fost găsită",
      "recipeNotFoundMessage": "Ne pare rău, rețeta solicitată nu există.",
      "backToHome": "Înapoi la Pagina Principală",
      "scaleIngredients": "Scalează Ingredientele",
      "servingMultiplier": "Multiplicator Porții",
      "meatType": "Tip de Carne",
      "vegetables": "Legume",
      "sauce": "Sos",
      "cookingMethod": "Metodă de Gătit",
      "viewRecipe": "Vezi Rețeta",
      "aboutTitle": "Despre",
      "aboutDescription": "Bine ați venit la colecția noastră de rețete tradiționale și moderne. Aici veți găsi rețete delicioase cu instrucțiuni clare și ingrediente ușor de găsit.",
      "cookingBasicsTitle": "Bazele Gătitului",
      "readRecipeThoroughly": "Citiți Rețeta Complet",
      "readRecipeDescription": "Înainte de a începe să gătiți, citiți întreaga rețetă de la început până la sfârșit. Acest lucru vă ajută să înțelegeți pașii și să vă pregătiți mental pentru proces.",
      "miseEnPlace": "Pregătiți Toate Ingredientele (Mise en Place)",
      "miseEnPlaceDescription": "Pregătiți și măsurați toate ingredientele înainte de a începe să gătiți. Acest lucru face procesul de gătit mai fluid și mai plăcut.",
      "pantryStaples": "Produse de Bază pentru Cămară",
      "pantryStaplesDescription": "Păstrați întotdeauna în cămară: ulei, oțet, sare, piper, zahăr, făină, orez, paste, conserve de roșii, usturoi și ceapă. Aceste ingrediente de bază vă permit să pregătiți multe rețete.",
      "imageLoadError": "Imaginea nu a putut fi încărcată",
      "errorOccurred": "A apărut o eroare",
      "tryAgain": "Încercați din nou",
      "close": "Închide",
      "filters": "Filtre",
      "difficulty": "Dificultate",
      "clearAllFilters": "Șterge Toate Filtrele",
      "ingredient": "Ingredient",
      "cookType": "Metodă de Gătit",
      "sortBy": "Sortare",
      "sortField": "Sortare după",
      "sortOrder": "Ordine",
      "sortByName": "Nume",
      "sortByDateAdded": "Data Adăugării",
      "sortByPrepTime": "Timp",
      "sortByPrice": "Preț",
      "ascending": "Crescător",
      "descending": "Descrescător",
      "ingredientPrices": "Prețuri Ingrediente",
      "priceList": "Listă de Prețuri",
      "ingredientId": "ID Ingredient",
      "ingredientName": "Nume Ingredient",
      "unitType": "Tip Unitate",
      "price": "Preț",
      "perKilogram": "per kg",
      "perLiter": "per litru",
      "perPiece": "per bucată",
      "searchIngredients": "Caută ingrediente...",
      "groupByCategories": "Grupare pe Categorii",
      "showCategories": "Arată Categoriile",
      "hideCategories": "Ascunde Categoriile"
    },
    "en": {
      "loading": "Loading...",
      "home": "Home",
      "menu": "Menu",
      "more": "More",
      "welcome": "Welcome",
      "greetingTitle": "What's cooking today?",
      "greetingSubtitle": "no ads, no trackers, just great food",
      "filter": "Filter",
      "about": "About",
      "cookingBasics": "Cooking Basics",
      "recipe": "Recipe",
      "recipes": "Recipes",
      "allRecipes": "All Recipes",
      "ingredients": "Ingredients",
      "instructions": "Instructions",
      "nutrition": "Nutrition",
      "personalNotes": "Personal Notes",
      "prepTime": "Prep time",
      "prepTimeShort": "Prep time",
      "servings": "Servings",
      "increaseServings": "Increase servings",
      "decreaseServings": "Decrease servings",
      "resetChecklist": "Reset checklist",
      "checkedIngredients": "{checked} of {total} checked",
      "estimatedCost": "Estimated cost",
      "partialEstimate": "Partial estimate",
      "knownSubtotal": "Known subtotal",
      "recipeTotal": "Recipe total",
      "costUnavailable": "Cost unavailable",
      "priceUnavailable": "Unavailable",
      "perServing": "RON / serving",
      "costForServings": "For {count} servings",
      "costForOneServing": "For 1 serving",
      "estimatedPerServing": "Approximately {price} / serving",
      "knownPerServing": "Known subtotal per serving: {price}",
      "ingredientNotPriced": "1 ingredient not included.",
      "ingredientsNotPriced": "{count} ingredients not included.",
      "noIngredientsPriced": "No ingredient costs are available.",
      "costQuantityNote": "Estimates for the quantities used, not the cost of buying full packages.",
      "costAssumptions": "View ingredient prices and calculation assumptions",
      "costConversionNote": "Calculated from the site's reference prices. Teaspoons and tablespoons use approximate conversions; shop prices may vary. Quantities without an available conversion are not included.",
      "missingPriceReason": "No reference price is available for this ingredient.",
      "unsupportedUnitReason": "This quantity cannot be converted to the reference price unit.",
      "invalidPriceReason": "The reference price is missing or invalid.",
      "invalidQuantityReason": "The quantity or serving count is invalid.",
      "effortLevel": "Effort level",
      "effortLevel.easy": "Easy",
      "effortLevel.medium": "Medium",
      "effortLevel.hard": "Hard",
      "easy": "Easy",
      "medium": "Medium",
      "hard": "Hard",
      "minutes": "minutes",
      "language": "Language",
      "textSize": "Text size",
      "theme": "Theme",
      "preferences": "Preferences",
      "dark": "Dark",
      "light": "Light",
      "normal": "Normal",
      "large": "Large",
      "romanian": "Romanian",
      "english": "English",
      "category": "Category",
      "categories": "Categories",
      "filterByCategory": "Filter by Category",
      "allCategories": "All Categories",
      "filterByKeywords": "Filter by Keywords",
      "selectFilters": "Select Filters",
      "clearFilters": "Clear all filters",
      "noRecipesFound": "No recipes found",
      "pantryEmpty": "Looks like the pantry is empty!",
      "pantryEmptyMessage": "We couldn't find any recipes matching your current filters or search.",
      "noRecipesMessage": "There are no recipes matching the selected criteria.",
      "noIngredientsFound": "No ingredients found",
      "recipeNotFound": "Recipe not found",
      "recipeNotFoundMessage": "Sorry, the requested recipe does not exist.",
      "backToHome": "Back to Home",
      "scaleIngredients": "Scale Ingredients",
      "servingMultiplier": "Serving Multiplier",
      "meatType": "Meat Type",
      "vegetables": "Vegetables",
      "sauce": "Sauce",
      "cookingMethod": "Cooking Method",
      "viewRecipe": "View Recipe",
      "aboutTitle": "About",
      "aboutDescription": "Welcome to our collection of traditional and modern recipes. Here you will find delicious recipes with clear instructions and easy-to-find ingredients.",
      "cookingBasicsTitle": "Cooking Basics",
      "readRecipeThoroughly": "Read the Recipe Thoroughly",
      "readRecipeDescription": "Before you start cooking, read the entire recipe from start to finish. This helps you understand the steps and mentally prepare for the process.",
      "miseEnPlace": "Prepare All Ingredients (Mise en Place)",
      "miseEnPlaceDescription": "Prepare and measure all ingredients before you start cooking. This makes the cooking process smoother and more enjoyable.",
      "pantryStaples": "Pantry Staples",
      "pantryStaplesDescription": "Always keep in your pantry: oil, vinegar, salt, pepper, sugar, flour, rice, pasta, canned tomatoes, garlic, and onions. These basic ingredients allow you to prepare many recipes.",
      "imageLoadError": "Image could not be loaded",
      "errorOccurred": "An error occurred",
      "tryAgain": "Try again",
      "close": "Close",
      "filters": "Filters",
      "difficulty": "Difficulty",
      "clearAllFilters": "Clear All Filters",
      "ingredient": "Ingredient",
      "cookType": "Cooking Method",
      "sortBy": "Sort By",
      "sortField": "Sort By",
      "sortOrder": "Order",
      "sortByName": "Name",
      "sortByDateAdded": "Date Added",
      "sortByPrepTime": "Time",
      "sortByPrice": "Price",
      "ascending": "Ascending",
      "descending": "Descending",
      "ingredientPrices": "Ingredient Prices",
      "priceList": "Price List",
      "ingredientId": "Ingredient ID",
      "ingredientName": "Ingredient Name",
      "unitType": "Unit Type",
      "price": "Price",
      "perKilogram": "per kg",
      "perLiter": "per liter",
      "perPiece": "per piece",
      "searchIngredients": "Search ingredients...",
      "groupByCategories": "Group by Categories",
      "showCategories": "Show Categories",
      "hideCategories": "Hide Categories"
    }
  },
  "recipeBase": "http://localhost:5173/cookingbook/recipe/",
  "appBase": "http://localhost:5173/cookingbook/"
};
