/**
 * Regenerates shared/catalogue.js from the real recipe data.
 *
 * Run from the repo root:  node mocks/homepage-v2/shared/prepare.mjs
 *
 * Unlike the older mocks/homepage-proposals scaffold, this one does NOT copy
 * image binaries. Each recipe carries a repo-root-relative `image` path, so a
 * proposal page at mocks/homepage-v2/proposal-0N/index.html renders it as
 * `../../../` + recipe.image and the compare page uses `../../` + recipe.image.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const shared = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(shared, '../../..');
const readJson = relative => JSON.parse(fs.readFileSync(path.join(root, relative), 'utf8'));

const bundled = await build({
  entryPoints: [path.join(root, 'src/utils/pricing.ts')],
  bundle: true,
  platform: 'node',
  format: 'esm',
  write: false,
});
const { calculateRecipeCost } = await import(
  `data:text/javascript;base64,${Buffer.from(bundled.outputFiles[0].text).toString('base64')}`
);

const categories = readJson('src/data/categories.json');
const filters = readJson('src/data/filter-keywords.json').filter(filter => filter.type !== 'difficulty');
const translations = readJson('src/data/translations.json');
const recipes = [];

for (const category of categories) {
  const directory = path.join(root, 'src/data/recipes', category.id);
  for (const file of fs.readdirSync(directory).filter(name => name.endsWith('.json'))) {
    const recipe = JSON.parse(fs.readFileSync(path.join(directory, file), 'utf8'));
    const id = path.basename(file, '.json');
    const cost = calculateRecipeCost(recipe, 'en');
    recipes.push({
      id,
      title: recipe.title,
      category: category.id,
      minutes: recipe.prepTime,
      servings: recipe.servings,
      effort: recipe.effortLevel,
      keywords: recipe.keywords,
      ingredientCount: recipe.ingredients.length,
      stepCount: recipe.instructions?.en?.length ?? 0,
      price: cost.pricePerServing,
      priceStatus: cost.status,
      unpricedCount: cost.unpricedIngredientCount,
      image: `public/images/recipes/${category.id}/${id}.thumb.webp`,
      imageFull: `public/images/recipes/${category.id}/${id}.jpg`,
      dateAdded: recipe.dateAdded,
    });
  }
}

const payload = {
  brand: "Paul's Cookbook",
  recipeCount: recipes.length,
  categories,
  filters,
  recipes,
  translations,
  recipeBase: 'http://localhost:5173/cookingbook/recipe/',
  appBase: 'http://localhost:5173/cookingbook/',
};

fs.writeFileSync(
  path.join(shared, 'catalogue.js'),
  `/* Generated by prepare.mjs - do not edit by hand. */\nwindow.COOKBOOK_DATA = ${JSON.stringify(payload, null, 2)};\n`,
  'utf8'
);
console.log(`Prepared ${recipes.length} recipes across ${categories.length} categories.`);
